---
- name: Processing subnet {{ item_subnet.name }} on cloud {{ item_cloud.name }}"
  template:
   src: subnet.tf.j2
   dest: "{{ oAnsiformCloudBuilderExportDirectory }}/{{ item_cloud.name }}/{{ item_profile }}-{{ item_subnet.name }}-subnet.tf"
